name: capstone_focus
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-35.0.dev <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  flutter_custom_clippers: ^2.1.0
  cloud_firestore: ^4.8.5
  firebase_ui_firestore:
  provider: ^6.0.5
  flutter_tts: ^3.8.1
  audioplayers: ^4.1.0
  flutter_sound: ^9.2.13
  just_audio: ^0.9.34
  shared_preferences: ^2.2.2
  marquee: ^2.2.3
  firebase_database: ^10.2.7
  url_launcher: ^6.1.11
  confetti: ^0.7.0
  bonfire: ^2.6.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flame_audio: ^2.0.4
  flame: ^1.9.1
  flame_forge2d: ^0.15.0+1
  get_it: ^7.6.4
  uuid: ^3.0.7
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/avatar/
    - assets/gamelogos/game1.png
    - assets/gamelogos/game2.png
    - assets/gamelogos/game3.png
    - assets/dwarforgiant/dwarf1.png
    - assets/dwarforgiant/giant1.png
    - assets/dwarforgiant/trailbg.jpg
    - assets/bg.mp3
    - assets/logo/main.png
    - assets/logo/focusfinder.png
    - assets/dwarforgiant/dwarf.png
    - assets/dwarforgiant/giant.png
    - assets/dwarforgiant/main.jpg
    - assets/gamelogos/game4.png
    - assets/gamelogos/game5.png
    - assets/gamelogos/game6.png
    - assets/tetris/tetbg.png
    - assets/tetris/tet.mp3
    - assets/spotthedif/score.png
    - assets/spotthedif/lvl1/correct.png
    - assets/spotthedif/lvl1/wrong.png
    - assets/spotthedif/lvl2/correct.png
    - assets/spotthedif/lvl2/wrong.png
    - assets/spotthedif/lvl3/correct.png
    - assets/spotthedif/lvl3/wrong.png
    - assets/spotthedif/lvl4/correct.png
    - assets/spotthedif/lvl4/wrong.png
    - assets/spotthedif/lvl5/wrong.png
    - assets/spotthedif/lvl5/correct.png
    - assets/spotthedif/lvl6/correct.png
    - assets/spotthedif/lvl6/wrong.png
    - assets/spotthedif/lvl7/correct.png
    - assets/spotthedif/lvl7/wrong.png
    - assets/spotthedif/lvl8/correct.png
    - assets/spotthedif/lvl8/wrong.png
    - assets/spotthedif/lvl9/correct.png
    - assets/spotthedif/lvl9/wrong.png
    - assets/spotthedif/lvl10/correct.png
    - assets/spotthedif/lvl10/wrong.png
    - assets/find10/1.png
    - assets/find10/2.png
    - assets/find10/3.png
    - assets/find10/4.png
    - assets/find10/5.png
    - assets/find10/6.png
    - assets/find10/7.png
    - assets/find10/8.png
    - assets/find10/9.png
    - assets/find10/find10bg.png
    - assets/find10/bg.png
    - assets/find10/fin.png
    - assets/tetris/pop.mp3
    - assets/find10/testbg10.png
    - assets/mainbg.png
    - assets/dwarforgiant/testbg.jpg
    - assets/spotthedif/level_1_ball_theme/ball_correct_1.png
    - assets/spotthedif/level_1_ball_theme/ball_wrong_1.png
    - assets/spotthedif/level_1_ball_theme/ball_correct_2.png
    - assets/spotthedif/level_1_ball_theme/ball_wrong_2.png
    - assets/spotthedif/level_1_ball_theme/ball_correct_3.png
    - assets/spotthedif/level_1_ball_theme/ball_wrong_3.png
    - assets/spotthedif/level_1_ball_theme/ball_correct_4.png
    - assets/spotthedif/level_1_ball_theme/ball_wrong_4.png
    - assets/spotthedif/level_1_ball_theme/ball_correct_5.png
    - assets/spotthedif/level_1_ball_theme/ball_wrong_5.png
    - assets/spotthedif/level_1_ball_theme/ball_correct_6.png
    - assets/spotthedif/level_1_ball_theme/ball_wrong_6.png
    - assets/spotthedif/level_1_ball_theme/ball_correct_7.png
    - assets/spotthedif/level_1_ball_theme/ball_wrong_7.png
    - assets/spotthedif/level_1_ball_theme/ball_correct_8.png
    - assets/spotthedif/level_1_ball_theme/ball_wrong_8.png
    - assets/spotthedif/level_1_ball_theme/ball_correct_9.png
    - assets/spotthedif/level_1_ball_theme/ball_wrong_9.png
    - assets/spotthedif/level_1_ball_theme/ball_correct_10.png
    - assets/spotthedif/level_1_ball_theme/ball_wrong_10.png
    - assets/spotthedif/level_2_cars_theme/1 diff.png
    - assets/spotthedif/level_2_cars_theme/1.png
    - assets/spotthedif/level_2_cars_theme/2 diff.png
    - assets/spotthedif/level_2_cars_theme/2.png
    - assets/spotthedif/level_2_cars_theme/3 diff.png
    - assets/spotthedif/level_2_cars_theme/3.png
    - assets/spotthedif/level_2_cars_theme/4 diff.png
    - assets/spotthedif/level_2_cars_theme/4.png
    - assets/spotthedif/level_2_cars_theme/5 diff.png
    - assets/spotthedif/level_2_cars_theme/5.png
    - assets/spotthedif/level_2_cars_theme/6 diff.png
    - assets/spotthedif/level_2_cars_theme/6.png
    - assets/spotthedif/level_2_cars_theme/7 diff.png
    - assets/spotthedif/level_2_cars_theme/7.png
    - assets/spotthedif/level_2_cars_theme/8 diff.png
    - assets/spotthedif/level_2_cars_theme/8.png
    - assets/spotthedif/level_2_cars_theme/9 diff.png
    - assets/spotthedif/level_2_cars_theme/9.png
    - assets/spotthedif/level_2_cars_theme/10 diff.png
    - assets/spotthedif/level_2_cars_theme/10.png
    # level 3
    - assets/spotthedif/level_3_cats_theme/1 diff.png
    - assets/spotthedif/level_3_cats_theme/1.png
    - assets/spotthedif/level_3_cats_theme/2 diff.png
    - assets/spotthedif/level_3_cats_theme/2.png
    - assets/spotthedif/level_3_cats_theme/3 diff.png
    - assets/spotthedif/level_3_cats_theme/3.png
    - assets/spotthedif/level_3_cats_theme/4 diff.png
    - assets/spotthedif/level_3_cats_theme/4.png
    - assets/spotthedif/level_3_cats_theme/5 diff.png
    - assets/spotthedif/level_3_cats_theme/5.png
    - assets/spotthedif/level_3_cats_theme/6 diff.png
    - assets/spotthedif/level_3_cats_theme/6.png
    - assets/spotthedif/level_3_cats_theme/7 diff.png
    - assets/spotthedif/level_3_cats_theme/7.png
    - assets/spotthedif/level_3_cats_theme/8 diff.png
    - assets/spotthedif/level_3_cats_theme/8.png
    - assets/spotthedif/level_3_cats_theme/9 diff.png
    - assets/spotthedif/level_3_cats_theme/9.png
    - assets/spotthedif/level_3_cats_theme/10 diff.png
    - assets/spotthedif/level_3_cats_theme/10.png
    # level 4
    - assets/spotthedif/level_4_clothes_theme/1 diff.png
    - assets/spotthedif/level_4_clothes_theme/1.png
    - assets/spotthedif/level_4_clothes_theme/2 diff.png
    - assets/spotthedif/level_4_clothes_theme/2.png
    - assets/spotthedif/level_4_clothes_theme/3 diff.png
    - assets/spotthedif/level_4_clothes_theme/3.png
    - assets/spotthedif/level_4_clothes_theme/4 diff.png
    - assets/spotthedif/level_4_clothes_theme/4.png
    - assets/spotthedif/level_4_clothes_theme/5 diff.png
    - assets/spotthedif/level_4_clothes_theme/5.png
    - assets/spotthedif/level_4_clothes_theme/6 diff.png
    - assets/spotthedif/level_4_clothes_theme/6.png
    - assets/spotthedif/level_4_clothes_theme/7 diff.png
    - assets/spotthedif/level_4_clothes_theme/7.png
    - assets/spotthedif/level_4_clothes_theme/8 diff.png
    - assets/spotthedif/level_4_clothes_theme/8.png
    - assets/spotthedif/level_4_clothes_theme/9 diff.png
    - assets/spotthedif/level_4_clothes_theme/9.png
    - assets/spotthedif/level_4_clothes_theme/10 diff.png
    - assets/spotthedif/level_4_clothes_theme/10.png
    # level 5
    - assets/spotthedif/level_5_cups_theme/1 diff.png
    - assets/spotthedif/level_5_cups_theme/1.png
    - assets/spotthedif/level_5_cups_theme/2 diff.png
    - assets/spotthedif/level_5_cups_theme/2.png
    - assets/spotthedif/level_5_cups_theme/3 diff.png
    - assets/spotthedif/level_5_cups_theme/3.png
    - assets/spotthedif/level_5_cups_theme/4 diff.png
    - assets/spotthedif/level_5_cups_theme/4.png
    - assets/spotthedif/level_5_cups_theme/5 diff.png
    - assets/spotthedif/level_5_cups_theme/5.png
    - assets/spotthedif/level_5_cups_theme/6 diff.png
    - assets/spotthedif/level_5_cups_theme/6.png
    - assets/spotthedif/level_5_cups_theme/7 diff.png
    - assets/spotthedif/level_5_cups_theme/7.png
    - assets/spotthedif/level_5_cups_theme/8 diff.png
    - assets/spotthedif/level_5_cups_theme/8.png
    - assets/spotthedif/level_5_cups_theme/9 diff.png
    - assets/spotthedif/level_5_cups_theme/9.png
    - assets/spotthedif/level_5_cups_theme/10 diff.png
    - assets/spotthedif/level_5_cups_theme/10.png
    # level 6
    - assets/spotthedif/level_6_dishes_theme/1 diff.png
    - assets/spotthedif/level_6_dishes_theme/1.png
    - assets/spotthedif/level_6_dishes_theme/2 diff.png
    - assets/spotthedif/level_6_dishes_theme/2.png
    - assets/spotthedif/level_6_dishes_theme/3 diff.png
    - assets/spotthedif/level_6_dishes_theme/3.png
    - assets/spotthedif/level_6_dishes_theme/4 diff.png
    - assets/spotthedif/level_6_dishes_theme/4.png
    - assets/spotthedif/level_6_dishes_theme/5 diff.png
    - assets/spotthedif/level_6_dishes_theme/5.png
    - assets/spotthedif/level_6_dishes_theme/6 diff.png
    - assets/spotthedif/level_6_dishes_theme/6.png
    - assets/spotthedif/level_6_dishes_theme/7 diff.png
    - assets/spotthedif/level_6_dishes_theme/7.png
    - assets/spotthedif/level_6_dishes_theme/8 diff.png
    - assets/spotthedif/level_6_dishes_theme/8.png
    - assets/spotthedif/level_6_dishes_theme/9 diff.png
    - assets/spotthedif/level_6_dishes_theme/9.png
    - assets/spotthedif/level_6_dishes_theme/10 diff.png
    - assets/spotthedif/level_6_dishes_theme/10.png
    # level 7
    - assets/spotthedif/level_7_dogs_theme/1 diff.png
    - assets/spotthedif/level_7_dogs_theme/1.png
    - assets/spotthedif/level_7_dogs_theme/2 diff.png
    - assets/spotthedif/level_7_dogs_theme/2.png
    - assets/spotthedif/level_7_dogs_theme/3 diff.png
    - assets/spotthedif/level_7_dogs_theme/3.png
    - assets/spotthedif/level_7_dogs_theme/4 diff.png
    - assets/spotthedif/level_7_dogs_theme/4.png
    - assets/spotthedif/level_7_dogs_theme/5 diff.png
    - assets/spotthedif/level_7_dogs_theme/5.png
    - assets/spotthedif/level_7_dogs_theme/6 diff.png
    - assets/spotthedif/level_7_dogs_theme/6.png
    - assets/spotthedif/level_7_dogs_theme/7 diff.png
    - assets/spotthedif/level_7_dogs_theme/7.png
    - assets/spotthedif/level_7_dogs_theme/8 diff.png
    - assets/spotthedif/level_7_dogs_theme/8.png
    - assets/spotthedif/level_7_dogs_theme/9 diff.png
    - assets/spotthedif/level_7_dogs_theme/9.png
    - assets/spotthedif/level_7_dogs_theme/10 diff.png
    - assets/spotthedif/level_7_dogs_theme/10.png
    # level 8
    - assets/spotthedif/level_8_house_theme/1 diff.png
    - assets/spotthedif/level_8_house_theme/1.png
    - assets/spotthedif/level_8_house_theme/2 diff.png
    - assets/spotthedif/level_8_house_theme/2.png
    - assets/spotthedif/level_8_house_theme/3 diff.png
    - assets/spotthedif/level_8_house_theme/3.png
    - assets/spotthedif/level_8_house_theme/4 diff.png
    - assets/spotthedif/level_8_house_theme/4.png
    - assets/spotthedif/level_8_house_theme/5 diff.png
    - assets/spotthedif/level_8_house_theme/5.png
    - assets/spotthedif/level_8_house_theme/6 diff.png
    - assets/spotthedif/level_8_house_theme/6.png
    - assets/spotthedif/level_8_house_theme/7 diff.png
    - assets/spotthedif/level_8_house_theme/7.png
    - assets/spotthedif/level_8_house_theme/8 diff.png
    - assets/spotthedif/level_8_house_theme/8.png
    - assets/spotthedif/level_8_house_theme/9 diff.png
    - assets/spotthedif/level_8_house_theme/9.png
    - assets/spotthedif/level_8_house_theme/10 diff.png
    - assets/spotthedif/level_8_house_theme/10.png
    # level 9
    - assets/spotthedif/level_9_shoes_theme/1 diff.png
    - assets/spotthedif/level_9_shoes_theme/1.png
    - assets/spotthedif/level_9_shoes_theme/2 diff.png
    - assets/spotthedif/level_9_shoes_theme/2.png
    - assets/spotthedif/level_9_shoes_theme/3 diff.png
    - assets/spotthedif/level_9_shoes_theme/3.png
    - assets/spotthedif/level_9_shoes_theme/4 diff.png
    - assets/spotthedif/level_9_shoes_theme/4.png
    - assets/spotthedif/level_9_shoes_theme/5 diff.png
    - assets/spotthedif/level_9_shoes_theme/5.png
    - assets/spotthedif/level_9_shoes_theme/6 diff.png
    - assets/spotthedif/level_9_shoes_theme/6.png
    - assets/spotthedif/level_9_shoes_theme/7 diff.png
    - assets/spotthedif/level_9_shoes_theme/7.png
    - assets/spotthedif/level_9_shoes_theme/8 diff.png
    - assets/spotthedif/level_9_shoes_theme/8.png
    - assets/spotthedif/level_9_shoes_theme/9 diff.png
    - assets/spotthedif/level_9_shoes_theme/9.png
    - assets/spotthedif/level_9_shoes_theme/10 diff.png
    - assets/spotthedif/level_9_shoes_theme/10.png
    # level 10
    - assets/spotthedif/level_10_trees_theme/1 diff.png
    - assets/spotthedif/level_10_trees_theme/1.png
    - assets/spotthedif/level_10_trees_theme/2 diff.png
    - assets/spotthedif/level_10_trees_theme/2.png
    - assets/spotthedif/level_10_trees_theme/3 diff.png
    - assets/spotthedif/level_10_trees_theme/3.png
    - assets/spotthedif/level_10_trees_theme/4 diff.png
    - assets/spotthedif/level_10_trees_theme/4.png
    - assets/spotthedif/level_10_trees_theme/5 diff.png
    - assets/spotthedif/level_10_trees_theme/5.png
    - assets/spotthedif/level_10_trees_theme/6 diff.png
    - assets/spotthedif/level_10_trees_theme/6.png
    - assets/spotthedif/level_10_trees_theme/7 diff.png
    - assets/spotthedif/level_10_trees_theme/7.png
    - assets/spotthedif/level_10_trees_theme/8 diff.png
    - assets/spotthedif/level_10_trees_theme/8.png
    - assets/spotthedif/level_10_trees_theme/9 diff.png
    - assets/spotthedif/level_10_trees_theme/9.png
    - assets/spotthedif/level_10_trees_theme/10 diff.png
    - assets/spotthedif/level_10_trees_theme/10.png
    - assets/images/
    - assets/drawable/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Jomhuria
      fonts:
        - asset: assets/Jomhuria-Regular.ttf
          weight: 400
    - family: Rubik
      fonts:
        - asset: assets/Rubik-Light.ttf
          weight: 300
        - asset: assets/Rubik-SemiBold.ttf
          weight: 600
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
